---
sidebar: sidebar 
permalink: vmware/vmw-hybrid-dr-overview.html 
keywords: dr, draas, bluexp, disaster recovery, vmfs datastore, nfs datastore, overview 
summary: Esta seção do documento descreve a configuração do BlueXP DRaaS para configurar a recuperação de desastres de VMs VMware locais para outro site designado. 
---
= Visão geral
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A recuperação de desastres é a principal preocupação de todo administrador do VMware.  Como o VMware encapsula servidores inteiros em uma série de arquivos que compõem a máquina virtual, os administradores aproveitam técnicas baseadas em armazenamento em bloco, como clones, snapshots e réplicas, para proteger essas VMs.  Os arrays ONTAP oferecem replicação integrada para transferir dados de volume e, portanto, as máquinas virtuais que residem nos LUNs de armazenamento de dados designados, de um site para outro.  O BlueXP DRaaS integra-se ao vSphere e automatiza todo o fluxo de trabalho para failover e failback perfeitos em caso de desastre.  Ao combinar a replicação de armazenamento com a automação inteligente, os administradores agora têm uma maneira gerenciável não apenas de configurar, automatizar e testar planos de recuperação de desastres, mas também os meios para executá-los facilmente em caso de desastre.

As partes mais demoradas de um failover de DR em um ambiente VMware vSphere são a execução das etapas necessárias para inventariar, registrar, reconfigurar e ligar as VMs no site de DR.  Uma solução ideal tem um RPO baixo (medido em minutos) e um RTO baixo (medido em minutos a horas).  Um fator que muitas vezes é negligenciado em uma solução de DR é a capacidade de testar a solução de DR de forma eficiente em um intervalo periódico.

Para arquitetar uma solução de DR, tenha em mente os seguintes fatores:

* O objetivo do tempo de recuperação (RTO).  O RTO é a rapidez com que uma empresa pode se recuperar de um desastre ou, mais especificamente, quanto tempo leva para executar o processo de recuperação para tornar os serviços empresariais disponíveis novamente.
* O objetivo do ponto de recuperação (RPO).  O RPO é a idade dos dados recuperados depois de terem sido disponibilizados, em relação ao momento em que o desastre ocorreu.
* Escalabilidade e adaptabilidade.  Esse fator inclui a capacidade de aumentar os recursos de armazenamento gradualmente conforme a demanda aumenta.


Para mais informações técnicas sobre as soluções disponíveis, consulte:

* link:vmw-hybrid-dr-nfs.html["DR usando BlueXP DRaaS para datastores NFS"]
* link:vmw-hybrid-dr-vmfs.html["DR usando BlueXP DRaaS para datastores VMFS"]

