---
sidebar: sidebar 
permalink: vmware/vmw-hybrid-compute-config.html 
keywords: NetApp Solutions, amazon, vmc, aws, microsoft azure, avs, azure, google cloud, gcp, gcve, vmware managed cloud, enterprise, hybrid, cloud, config, configuration 
summary:  
---
= Configurando o ambiente de virtualização no provedor de nuvem
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Detalhes sobre como configurar o ambiente de virtualização em cada um dos hiperescaladores suportados são abordados aqui.

[role="tabbed-block"]
====
.AWS / VMC
--
Esta seção descreve como configurar e gerenciar o VMware Cloud on AWS SDDC e usá-lo em combinação com as opções disponíveis para conectar o armazenamento NetApp .


NOTE: O armazenamento no convidado é o único método suportado para conectar o Cloud Volumes ONTAP ao AWS VMC.

O processo de configuração pode ser dividido nas seguintes etapas:

* Implantar e configurar o VMware Cloud para AWS
* Conecte o VMware Cloud ao FSx ONTAP


Veja o detalhadolink:../vmware/vmw-aws-vmc-setup.html["etapas de configuração para VMC"] .

--
.Azure / AVS
--
Esta seção descreve como configurar e gerenciar o Azure VMware Solution e usá-lo em combinação com as opções disponíveis para conectar o armazenamento NetApp .


NOTE: O armazenamento no convidado é o único método suportado para conectar o Cloud Volumes ONTAP ao Azure VMware Solution.

O processo de configuração pode ser dividido nas seguintes etapas:

* Registre o provedor de recursos e crie uma nuvem privada
* Conectar-se a um gateway de rede virtual ExpressRoute novo ou existente
* Valide a conectividade de rede e acesse a nuvem privada


Veja o detalhadolink:azure-setup.html["etapas de configuração para AVS"] .

--
.GCP / GCVE
--
Esta seção descreve como configurar e gerenciar o GCVE e usá-lo em combinação com as opções disponíveis para conectar o armazenamento NetApp .


NOTE: O armazenamento no convidado é o único método suportado para conectar o Cloud Volumes ONTAP e o Google Cloud NetApp Volumes ao GCVE.

O processo de configuração pode ser dividido nas seguintes etapas:

* Implantar e configurar o GCVE
* Habilitar acesso privado ao GCVE


Veja o detalhadolink:gcp-setup.html["etapas de configuração para GCVE"] .

--
====