---
sidebar: sidebar 
permalink: vmware/vmw-azure-avs-storage.html 
keywords: azure, netapp, anf, storage, options, nfs, supplemental, cvo 
summary: O armazenamento NetApp pode ser anexado ao Azure VMware Service como armazenamento conectado a convidado ou suplementar. 
---
= Serviço de Virtualização do Azure: Opções para usar o armazenamento NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O armazenamento NetApp pode ser anexado ao Azure VMware Service como armazenamento conectado a convidado ou suplementar.



== Azure NetApp Files (ANF) como um armazenamento de dados NFS suplementar

O suporte ao armazenamento de dados NFS foi introduzido com o ESXi versão 3 em implantações locais, o que ampliou muito os recursos de armazenamento do vSphere.

Executar o vSphere no NFS é uma opção amplamente adotada para implantações de virtualização no local porque oferece alto desempenho e estabilidade.  Se você tiver um armazenamento conectado à rede (NAS) significativo em um datacenter local, considere implantar um SDDC de solução VMware no Azure com armazenamentos de dados do Azure NetApp File para superar desafios de capacidade e desempenho.

O Azure NetApp Files é criado com base no software de gerenciamento de dados NetApp ONTAP , líder do setor e altamente disponível.  Os serviços do Microsoft Azure são agrupados em três categorias: básicos, principais e especializados.  O Azure NetApp Files está na categoria especializada e é apoiado por hardware já implantado em muitas regiões.  Com alta disponibilidade (HA) integrada, o Azure NetApp Files protege seus dados da maioria das interrupções e oferece um SLA líder do setor com 99,99% de tempo de atividade.

Para mais informações sobre o ANF como um armazenamento de dados NFS suplementar, visite:

* link:vmw-azure-avs-nfs-ds-overview.html["ANF como um armazenamento de dados NFS suplementar: visão geral"]
* link:vmw-azure-avs-nfs-ds-config.html["Opção suplementar de armazenamento de dados NFS no Azure"]




== Azure NetApp Files (ANF) como armazenamento conectado a convidados

O Azure NetApp Files traz gerenciamento e armazenamento de dados de nível empresarial para o Azure para que você possa gerenciar suas cargas de trabalho e aplicativos com facilidade.  Migre suas cargas de trabalho para a nuvem e execute-as sem sacrificar o desempenho.

O Azure NetApp Files remove obstáculos para que você possa mover todos os seus aplicativos baseados em arquivos para a nuvem.  Pela primeira vez, você não precisa reestruturar seus aplicativos e obtém armazenamento persistente para seus aplicativos sem complexidade.

Como o serviço é fornecido por meio do Portal do Microsoft Azure, os usuários experimentam um serviço totalmente gerenciado como parte do Contrato Corporativo da Microsoft.  Suporte de classe mundial, gerenciado pela Microsoft, lhe dá total tranquilidade.  Esta solução única permite que você adicione cargas de trabalho multiprotocolo de forma rápida e fácil. Você pode criar e implantar aplicativos baseados em arquivos do Windows e do Linux, mesmo para ambientes legados.

Para mais informações, visitelink:vmw-azure-avs-guest-storage.html#anf["ANF como armazenamento conectado para convidados"] .



== Cloud Volumes ONTAP (CVO) como armazenamento conectado a convidados

O Cloud Volumes ONTAP (CVO) é a solução de gerenciamento de dados em nuvem líder do setor, desenvolvida no software de armazenamento ONTAP da NetApp, disponível nativamente na Amazon Web Services (AWS), Microsoft Azure e Google Cloud Platform (GCP).

É uma versão definida por software do ONTAP que consome armazenamento nativo da nuvem, permitindo que você tenha o mesmo software de armazenamento na nuvem e no local, reduzindo a necessidade de treinar novamente sua equipe de TI em métodos totalmente novos para gerenciar seus dados.

O CVO oferece aos clientes a capacidade de mover dados facilmente da borda para o data center, para a nuvem e vice-versa, reunindo sua nuvem híbrida — tudo gerenciado com um console de gerenciamento de painel único, o NetApp Cloud Manager.

Por design, o CVO oferece desempenho extremo e recursos avançados de gerenciamento de dados para satisfazer até mesmo seus aplicativos mais exigentes na nuvem

Para mais informações, visitelink:vmw-azure-avs-guest-storage.html#azure-cvo["CVO como armazenamento conectado a convidados"] .
