---
sidebar: sidebar 
permalink: google/gcp-gcnv-firewall.html 
keywords: tcp, nfs, smb share, kerberos, active directory, dns 
summary: O Google Cloud NetApp Volumes expõe várias portas TCP para atender compartilhamentos NFS e SMB. 
---
= Firewall
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O Google Cloud NetApp Volumes expõe várias portas TCP para atender compartilhamentos NFS e SMB:

* https://docs.cloud.google.com/netapp/volumes/docs/connect-clients/connect-nfs-clients#firewall_rules_for_nfs_volumes_access["Portas necessárias para acesso NFS"^]
* https://docs.cloud.google.com/netapp/volumes/docs/connect-clients/connect-smb-clients#firewall_rules_for_smb_volumes_access["Portas necessárias para acesso SMB"^]


Além disso, as configurações de SMB, NFS com LDAP, incluindo Kerberos, e de protocolo duplo exigem acesso a um domínio do Windows Active Directory. As conexões do Active Directory devem ser https://docs.cloud.google.com/netapp/volumes/docs/configure-and-use/active-directory/create-ad-policy["configurado"^] feitas por região. Os controladores de domínio (DCs) do Active Directory são identificados usando https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/7fcdce70-5205-44d6-9c3a-260e616a2f04["Descoberta de DC baseada em DNS"^] os servidores DNS especificados. Qualquer um dos DCs retornados será usado. A lista de DCs elegíveis pode ser limitada pela especificação de um site do Active Directory.

O Google Cloud NetApp Volumes se comunica usando endereços IP do intervalo CIDR alocado com o comando `gcloud compute address` enquanto https://docs.cloud.google.com/netapp/volumes/docs/plan-and-prepare/networking#configure_private_services_access["integração do Google Cloud NetApp Volumes"^]. Você pode usar esse CIDR como endereços de origem para configurar firewalls de entrada para seus controladores de domínio do Active Directory.

Os controladores de domínio do Active Directory devem https://docs.cloud.google.com/netapp/volumes/docs/plan-and-prepare/security-considerations["expor portas para os CIDRs do Google Cloud NetApp Volumes, conforme mencionado aqui"^].
