---
sidebar: sidebar 
permalink: google/gcp-gcnv-data-encrypt-at-rest.html 
keywords: aes-256 encryption, cmek 
summary: Todos os volumes no Google Cloud NetApp Volumes são criptografados em repouso usando criptografia AES-256, o que significa que todos os dados do usuário gravados na mídia são criptografados e só podem ser descriptografados com uma chave por volume. 
---
= Criptografia de dados em repouso
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Todos os volumes no Google Cloud NetApp Volumes são criptografados em repouso usando criptografia AES-256, o que significa que todos os dados do usuário gravados na mídia são criptografados e só podem ser descriptografados com uma chave por volume.

* Para o NetApp Volumes-SW, são usadas chaves geradas pelo Google.
* Para o NetApp Volumes-Performance, as chaves por volume são armazenadas em um gerenciador de chaves integrado ao Google Cloud NetApp Volumes.


A partir de novembro de 2021, a funcionalidade de chaves de criptografia gerenciadas pelo cliente (CMEK) foi disponibilizada.  Isso permite que você criptografe as chaves por volume com uma chave mestra por projeto e por região hospedada em https://cloud.google.com/kms/docs["Serviço de gerenciamento de chaves do Google (KMS)."^] O KMS permite que você anexe gerenciadores de chaves externos.

Para obter informações sobre como configurar o KMS para NetApp Volumes-Performance, consulte https://cloud.google.com/architecture/partners/netapp-cloud-volumes/customer-managed-keys?hl=en_US["Configurando chaves de criptografia gerenciadas pelo cliente"^] .
