---
sidebar: sidebar 
permalink: videos/hmc-aws-videos.html 
summary: Vídeos e demonstrações apresentando soluções de multicloud híbrida da AWS com NetApp 
keywords: hybrid cloud, rosa, fsx ontap, azure vmware, netapp hci, videos, demos 
---
= Assista a vídeos sobre soluções multicloud híbridas para Amazon Web Services com NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Explore a abrangente biblioteca de vídeos da NetApp apresentando soluções multicloud híbridas para AWS com NetApp.  Assista a vídeos sobre armazenamento conectado a convidados, economia de TCO, armazenamentos de dados suplementares e fluxos de trabalho de migração para VMware Cloud on AWS e Amazon FSx for ONTAP, incluindo cenários Windows e Linux.



== Armazenamento conectado ao convidado

.Armazenamento conectado de convidado do Windows com FSx ONTAP usando iSCSI
video::0d03e040-634f-4086-8cb5-b01200fb8515[panopto,width=360]
.Armazenamento conectado para convidados Linux com FSx ONTAP usando NFS
video::c3befe1b-4f32-4839-a031-b01200fb6d60[panopto,width=360]


== TCO e armazenamentos de dados suplementares

.Economia de TCO do VMware Cloud na AWS com o Amazon FSx ONTAP
video::f0fedec5-dc17-47af-8821-b01200f00e08[panopto,width=360]
.Armazenamento de dados suplementar do VMware Cloud on AWS com Amazon FSx ONTAP
video::2065dcc1-f31a-4e71-a7d5-b01200f01171[panopto,width=360]


== Fluxos de trabalho de migração (HCX)

.Implantação e configuração do VMware HCX para VMC
video::6132c921-a44c-4c81-aab7-b01200fb5d29[panopto,width=360]
.Demonstração de migração do vMotion com VMware HCX para VMC e FSx ONTAP
video::52661f10-3f90-4f3d-865a-b01200f06d31[panopto,width=360]
.Demonstração de migração a frio com VMware HCX para VMC e FSx ONTAP
video::685c0dc2-9d8a-42ff-b46d-b01200f056b0[panopto,width=360]